### ISSUE TITLE
wrong colors shown for Bob's mods

### ISSUE THREAD

**Issue by sparr** [danielbrauer/DiscoScience#1]
Bob's mods use the science pack colors in a different order. Apparently there's a way to read which graphic is being used, or something?

**Comment by danielbrauer** [comment]
Unfortunately there's no way to figure out what colour an icon is from the API, so this needs to be done manually. I need to figure out how much work this would be for the most-used mods out there.

**Comment by sparr** [comment]
During the final fixes data stage you could look for science items that use icons that you already know the colors for, and map them that way. This would be compatible with the parts of Bob's mods that just rearranges the existing icons.

**Comment by danielbrauer** [comment]
Ah yeah, doing it by icon is a good idea, even if the colours themselves still have to be matched manually. I’ll give that a try.

**Comment by danielbrauer** [comment]
Any new guidance on sneaking a table out of the data phase? It looks like flying-text's order field is limited to 200 characters. I can break it up for now.

**Comment by danielbrauer** [comment]
Addressed in ccd597dcef1195f58ae040829fdd0c9562c379c8 with flying-text for the time being.
