### ISSUE TITLE
Your mod is RAM hungry and probably desyncs. Here is how to fix it

### ISSUE THREAD

**Issue by Bilka2** [danielbrauer/DiscoScience#2]
See https://forums.factorio.com/viewtopic.php?p=422307#p422307

What he means with using a lua object as a key: https://github.com/danielbrauer/DiscoScience/blob/master/control.lua#L69

What he means with mutable game data is https://github.com/danielbrauer/DiscoScience/blob/master/control.lua#L13 and https://github.com/danielbrauer/DiscoScience/blob/master/control.lua#L17 - this is modified all over the place and not stored in global.

There are probably more instances of this, but I think seeing what he means will help you find the rest.

**Comment by danielbrauer** [comment]
Oh wow yeah that's terrible. Thanks for the heads up!

**Comment by danielbrauer** [comment]
Ok, I think these issues are addressed in c5001cdad43e4a23bbcb4dee196ee98d10aa2ab9 and 4163bdbc5ea5a5a31ae14aabfeba8ddd75d0375f. Thanks for explaining in detail.
