### ISSUE TITLE
Compatibility with The Ruins Mod (changing force of labs)

### ISSUE THREAD

**Issue by Bilka2** [danielbrauer/DiscoScience#6]
Hey, [the ruins mod](https://github.com/Bilka2/AbandonedRuins) spawns labs on the neutral force and then allows players to change those to their own force via a selection tool. This leads to a problem with your mod: There is no (vanilla) event for when entities change force, so your data structure is never updated with the new lab force, and players receive an error when they pick up the lab/the animation doesnt work correctly. 

Since there is no vanilla event for entities changing force, there is no super easy way for you to handle this case. I propose that I could add a custom event that I raise when the player changes the force of entities via my mod. And you can subscribe to it to update your data structure. This needs extra code for both our mods, but should allow them to work together flawlessly. In case you've not really interacted with custom mod events, here is an example from one of my other mods: https://github.com/Bilka2/NewGamePlus/blob/master/control.lua#L33

**Comment by danielbrauer** [comment]
Hi Bilka,

I'd be happy to add support for such an event. Let me know when you have a chance to implement it!

Thanks,
Daniel

**Comment by Bilka2** [comment]
I added the event with https://github.com/Bilka2/AbandonedRuins/commit/b2da51da8e6a6038025e425f4c4cc53f246782c1.

I did some crude testing with your mod by adding the event subscription to on_init/on_load and calling labRenderers.reloadLabs() there: Everything worked correctly.

**Comment by danielbrauer** [comment]
Super. I made a function to transfer labs between force structures, and linked it up with an optional dependency on your mod. Thanks again for working to make our mods compatible!

(Addressed in 34cbab8f567deb33fe67067b15e9064eb4905696)

**Comment by Bilka2** [comment]
Thank you to you too.
