### ISSUE TITLE
Illumination does not render properly on surfaces other than Nauvis

### ISSUE THREAD

**Issue by MagmaMcFry** [danielbrauer/DiscoScience#7]
Original report: https://github.com/MagmaMcFry/Factorissimo2/issues/66

Labs on other surfaces stop being animated in certain situations.

Probable fix:

https://github.com/danielbrauer/DiscoScience/blob/937e1858d137a0bdc26ce37b1246e3c530a878a4/src/core/labRenderers.lua#L93-L100

Instead of only checking the default surface for labs, this method should loop over all surfaces in the game.

**Comment by ExE-Boss** [comment]
This will need to be fixed by the time the **Space Age** DLC is released.

**Comment by danielbrauer** [comment]
Addressed by https://github.com/danielbrauer/DiscoScience/pull/9
